apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetespredictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diabetespredictor
  template:
    metadata:
      labels:
        app: diabetespredictor
    spec:
      containers:
      - name: diabetespredictor
        image: whoolt/diabetespredictor-tw
        imagePullPolicy: Always
        command: ["flask"]
        args: ["run", "-h", "0.0.0.0", "--port=8080"]
---

apiVersion: v1
kind: Service
metadata:
  name: diabetespredictor-service
spec:
  type: NodePort
  selector:
    app: diabetespredictor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
